### ISSUE TITLE
Getting  "error": "The action did not produce a valid response and exited unexpectedly."

### ISSUE THREAD

**Issue by tleyden** [jthomas/ow#2]
In certain cases (maybe returning json over a certain size?) it's using chunked transfer encoding:

```
HTTP/1.1 200 OK.
Content-Type: application/json.
Date: Sat, 15 Jul 2017 06:13:13 GMT.
Transfer-Encoding: chunked.
.
```

I used `ngrep` to compare it with an identical go/docker based handler running in the python shim (openwhisk/dockerskeleton and invoking over stdio), and the headers look like this:

```
HTTP/1.1 200 OK.
Content-Type: application/json.
Content-Length: 8848.
Date: Sat, 15 Jul 2017 05:53:37 GMT.
.

```

And everything works.

Rough fix here: https://github.com/tleyden/ow/commit/2d5d63047c2ac28f0c4975af1f790fdf3c038691#diff-7bc507702220a47bdc39197b17416097

Is this an issue in OpenWhisk where it's not handling `Transfer-Encoding: chunked.` responses correctly?

**Comment by tleyden** [comment]
The key point is this line:

```
w.Header().Set("Content-Length", fmt.Sprintf("%v", len(b)))
```

Related StackOverflow thread: https://stackoverflow.com/questions/14315224/disable-chunked-encoding-for-http-server-responses

**Comment by jthomas** [comment]
Thanks for digging into this @tleyden. 

My Go is very rusty,  I'll defer to your experience in fixing this issue. It looks sensible from reading the context in those links.
